config/routes.rb
Rails.application.routes.draw do

  #sets my homepage 
  get '/' => 'sessions#welcome'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get'/popular_event' => 'listings#popular_event'

  resources :users do 
    resources :listings, only: [:index]
  end
  resources :locations 
  resources :events
  resources :pets
  resources :listings do 
    resources :events, only: [:new, :index]
  end
  
  resources :users do 
    resources :events, only: [:show]
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord

    belongs_to :author, class_name: "User"
    belongs_to :location
    has_many :events
    has_many :user_requestors, through: :events, source: :user_id

    validates :title, :content, :date_time, :location, presence: true
    scope :order_by_post_date, -> { order(created_at: :desc)} 
    scope :event_with_most_rsvps, -> {joins(:events).group(:id).order('COUNT(events.id) DESC')} 
    

    #custom method in order to allow us to find or create location
    #custom method unlike accepts_nested_attributes does not create duplicates 

    def location_attributes=(attributes)

        if !attributes[:name].blank?

        self.location = Location.find_or_create_by(attributes)

        end  
    end
    
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

    # before_action :set_listing, only: [:show, :edit, :update]

    def index

        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @listings = @user.authored_listings.order_by_post_date 
        else 
            @error = "User not Found" if params[:user_id]
            @listings = Listing.all.order_by_post_date
        end

    end

    def new

        @listing = Listing.new
        @listing.build_location 

    end
    
    def create

        @listing = Listing.create(listing_params)
        @listing.author_id = session[:user_id]
        
        # @listing.location_id = params[:listing][:location_id]
        if @listing.save
                redirect_to listings_path, notice: 'Listing was successfuly created.'
            else 
                @listing.build_location 
                render :new 
        end
    end

    def show 

        @listing = Listing.find(params[:id])
        
    end

    
    
    def edit

        @listing = Listing.find(params[:id])
        authorized_to_edit?

    end

    def update 

        @listing = Listing.find(params[:id])
        @listing.update(listing_params)
        authorized_to_edit? 
        redirect_to user_listings_path(current_user), notice: 'Listing was successfully updated.'
        
    end

    def destroy

        Listing.find(params[:id]).destroy
        redirect_to listings_path, notice: 'Listing was successfully destroyed'
        
    end

    def popular_event 

        @listings = Listing.event_with_most_rsvps
        
    end

    private
    
    def listing_params 

        params.require(:listing).permit(:title, :content, :date_time, :location_id, location_attributes: [:name])
        
    end

    def authorized_to_edit?

        redirect_to listings_path, notice: "You are not authorized to edit" if !@listing || @listing.author != current_user 

    end

    #dry method
    # def set_listing
    #     @listing = Listing.find_by(params[:id])
    #     redirect_to listings_path if !@listing
    # end
end

app/helpers/listings_helper.rb
module ListingsHelper

    def authorized_to_edit_listing?(listing)

        listing.author == current_user 
       
    end 

    def self_request?(listing)

        listing.author == current_user

    end 

    def authored_by_user?(listing)

        listing.author == current_user 

    end

   
   
end

app/views/listings/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @listing} %>

<%= form_for(@listing) do |f| %>
    <div class="field form-group">
    <%= f.label :title %> 
    <%= f.text_field :title, class: 'form-control' %>
    </div>
    <br>
    <br> 
    <div class="field form-group">
    <%= f.label :content %> 
    <%= f.text_area :content, class: 'form-control' %>
    </div>
    <br>
    <br> 
    <div class="field form-group">
    <%= f.label :date_time %>
    <%= f.datetime_local_field :date_time, class: 'form-control' %>
    </div>
    <br>
    <br> 
    <h4> Select a location:</h4>

    <%= f.label :location_id %> 
    <%= f.collection_select :location_id, Location.all, :id, :name, include_blank: 'Select One' %>
    <br>
    <br>
    <p> Or create a new location:</p>
    <%= f.fields_for :location do |l_location| %> 
        <%= l_location.label :name %>
        <%= l_location.text_field :name %> 
        <% end %> 
    <br>
    <br>
    <div class="field form-group">
    <%= f.submit class: 'btn btn-success' %>
    </div>
    <% end %> 

app/views/listings/edit.html.erb
<h1> Update Your Listing </h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<% if @user %> 

<div class="container p-3 my-3 bg-dark text-white"><h2>Here are your listings, <%= @user.username %></h2></div>

<% else %> 

<div class="jumbotron"> 

<h1>Paw Pals</h1>

</div>

<div class="container p-3 my-3 bg-dark text-white"> Recent Listings </div>

<% end %> 

<% @listings.each do |l| %>
    <h2><%= link_to l.title, listing_path(l) %></h2> Posted on: <%= l.created_at.strftime("%b %e, %l:%M %p") %>
     <% end %> 


  

app/views/listings/new.html.erb
<h1> Create a New Listing </h1>

<%= render 'form' %>

app/views/listings/popular_event.html.erb
<h1> Popular Events Organized by number of RSVPs </h1>
<br>
<br>
<% @listings.each do |l| %>
   <ul>
   <li> <%= l.title %> - Num. of RSVPS: <%= l.events.count %></li> 
   </ul>
    <% end %> 
  

    

app/views/listings/show.html.erb
<h1>Event Info </h1><br>

<h2><%= @listing.title %></h2>
    <br>
    <br> 
    <%= @listing.content %>
    <br> 
    <br>
    <p>Location: <%= @listing.location.name %></p>
    <p>Date/Time: <%= @listing.date_time.strftime("%b %e, %l:%M %p")  %></p>

    <% if !authored_by_user?(@listing) %>

            <p> Author: <%= link_to @listing.author.name, user_path(@listing.author) %></p>
        <% else %> 
            <p> Author: self </p>
    <% end %> 
    <p> Posted on: <%= @listing.created_at.strftime("%b %e, %l:%M %p") %></p>

    <% if !self_request?(@listing) %> 
            <p><%= link_to "Click to Join the Fun", new_listing_event_path(@listing), class:"btn btn-primary" %>
            <br>
            <br>
    <% end %>

<% if authorized_to_edit_listing?(@listing) %>

<%= link_to "Edit", edit_listing_path(@listing) %>
<%= button_to "Delete", listing_path(@listing), method: :delete, data: { confirm: 'Are you sure you want to delete this record?' }%> 

<% end %>