config/routes.rb
Rails.application.routes.draw do

  #sets my homepage 
  get '/' => 'sessions#welcome'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get'/popular_event' => 'listings#popular_event'

  resources :users do 
    resources :listings, only: [:index]
  end
  resources :locations 
  resources :events
  resources :pets
  resources :listings do 
    resources :events, only: [:new, :index]
  end
  
  resources :users do 
    resources :events, only: [:show]
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord

    belongs_to :user
    has_one_attached :profile_pic
    has_many :event_pets 
    has_many :events, through: :event_pets 
    # has_many :requests
    # has_many :listings 
    validates :name, :age, :size, :breed, :gender, presence: true 
    # validates :image, attached: true
    validates :size, inclusion: { in: %w(small medium large), message: "%{value} is not a valid size"}
    validates :age, inclusion:{ in: %w(puppy adolescent adult senior), message: "%{value} is not a valid age"}
    validates :gender, inclusion:{ in: %w(Female Male), message: "%{value} is not valid"}
    
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    def index

        @pets = Pet.all 
    
    end
    
    def new

        @pet = Pet.new 
       
    end
    
    def create 

        @pet = Pet.create(pet_params)
        @pet.user_id = session[:user_id]

        if @pet.save
                redirect_to user_path(current_user)
        else
            render :new
        end
    end

    def show

        @pet = Pet.find(params[:id])  

    end

    def edit 

        @pet = Pet.find(params[:id])
        authorized_to_edit?
    
    end

    def update 
        
        @pet = Pet.find(params[:id])
        @pet.update(pet_params)
        authorized_to_edit?
        redirect_to user_path(current_user)

    end

    def destroy  

        Pet.find(params[:id]).destroy 
        redirect_to user_path(current_user)
        
    end

    private

    #belongs to owner 
    def pet_params 
        params.require(:pet).permit(:name, :age, :size, :breed, :profile_pic, :gender)
    end

    def authorized_to_edit?

        redirect_to user_path(current_user), notice: "You are not authorized to edit" if !@pet || @pet.user != current_user 

    end
end

app/helpers/pets_helper.rb
module PetsHelper

    def authorized_to_edit_pet?(pet)

        pet.user == current_user
       
    end 

end

app/views/pets/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @pet} %>

<%= form_for(@pet) do |f| %>
    <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>
    </div>
    <br>
    <br>

    <div class="field form-group">
        <% if @pet.profile_pic.attached? %>
            <%= image_tag @pet.profile_pic, style: "width: 200px; display: block" %>
        <% end %> 
        
    <div class="field form-group">
        <%= f.label :profile_pic %>
        <%= f.file_field :profile_pic, accept: 'image/png, image/gif, image/jpeg', class: 'form-control'%>
        </div> 

    <br>
    <br> 
    <div class="field form-group">
    <%= f.label :age %>
    <%= f.select :age, ["puppy","adolescent","adult", "senior"], class: 'form-control' %>
    </div>
    <br>
    <br>
    <div class="field form-group">
    <p>Gender</p>
    <%= f.label 'gender', 'Female' %>
    <%= f.radio_button :gender, 'Female' %> 
    <%= f.label 'gender', 'Male' %>
    <%= f.radio_button :gender, 'Male' %> 
    </div> 
    <br>
    <br>
    <div class="field form-group">
    <%= f.label :size %>
    <%= f.select :size, ["small","medium","large"], class: 'form-control' %>
    </div>
    <br>
    <br>
    <div class="field form-group">
    <%= f.label :breed %>
    <%= f.text_field :breed, class: 'form-control' %>
    <br>
    <br>
    <div class="field form-group">
    <%= f.submit class: 'btn btn-success' %>
    </div>
    <% end %>

app/views/pets/edit.html.erb
<h1> Edit New Pet </h1> 

<%= render 'form' %>

app/views/pets/new.html.erb
<h1> Create a New Pet </h1> 

<%= render 'form' %>

app/views/pets/show.html.erb
<h1> Woof, Woof </h1>

<h2> <%= @pet.name.titleize %>'s Profile </h1> 

<% if @pet.profile_pic.attached? %>

    <img class="img-fluid" src="<%= (url_for(@pet.profile_pic))%>">

<% end %> 

<p><strong>Age:</strong> <%= @pet.age %></p>
<p><strong>Gender:</strong> <%= @pet.gender %></p>
<p><strong>Breed:</strong> <%= @pet.breed %></p>
<p><strong>Size:</strong> <%= @pet.size %></p> 


<% if authorized_to_edit_pet?(@pet)%>

<%= link_to "Edit", edit_pet_path(@pet) %>
<br>
<br> 
<%= button_to "Delete", pet_path(@pet), method: :delete, data: { confirm: 'Are you sure you want to delete this record?' }%> 

<% end %>
    