config/routes.rb
Rails.application.routes.draw do

  #sets my homepage 
  get '/' => 'sessions#welcome'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get'/popular_event' => 'listings#popular_event'

  resources :users do 
    resources :listings, only: [:index]
  end
  resources :locations 
  resources :events
  resources :pets
  resources :listings do 
    resources :events, only: [:new, :index]
  end
  
  resources :users do 
    resources :events, only: [:show]
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

    has_many :pets
    #sent requests
    has_many :events
    has_many :answered_listings, -> { order 'date_time asc'}, through: :events, source: :listing
    has_many :authored_listings, -> { order 'date_time asc'}, foreign_key: :author_id, class_name: "Listing"
    #received requests 
    has_many :received_events, through: :authored_listings, source: :events
    validates :username, uniqueness: true, presence: true
    validates :email, uniqueness: true, presence: true 
    has_secure_password

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.username = response[:info][:name]
            u.email = response[:info][:email]
            u.password = SecureRandom.hex(15)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    skip_before_action :login_required, :only => [:new, :create]

    def new

        @user = User.new

    end

    def create

        @user = User.create(user_params)

        if @user.save
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else 
            render :new 
        end

    end

    def show 

        @user = User.find_by(id: params[:id])
         
    end

    private
    
    def user_params
        params.require(:user).permit(:username, :email, :password, :name, :listing_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_event.html.erb
<h3> Hosted Events </h3><br>



<ul>
 <% @user.authored_listings.each do |e| %>
        <li><h4><%= link_to e.title, listing_path(e) %></li></h4><br>
        <ul>
        <li>Location: <%= e.location.name %></li>
        <li>Date & Time: <%= e.date_time.strftime("%b %e, %l:%M %p") %></li></br>
        </ul>
    <% end %> 
    </ul> 


<h3> Paw Pal Attendee </h3><br>

    <ul> 
    <% @user.answered_listings.each do |e| %>
        <li><h4><%= e.title %></h4></li><br>
        <ul>
        <li>Location: <%= e.location.name %></li>
        <li>Date & Time: <%= e.date_time.strftime("%b %e, %l:%M %p") %></li>
        <li>Hosted by: <%= link_to e.author.name, user_path(e.author) %> </li><br>
        </ul>
    <% end %>
    </ul>

app/views/users/_previous.html.erb
<h3> My Upcoming Hosted Events </h3>


 <% @user.received_events.each do |r| %> 

    <% if r.accept == true %> 
        <p> Appointment with: </p> 
        <ul>
        <li>Owner: <%= r.user.name %></li>
        <li>Dog: <%= r.pet.name %></li>
        <li>Date & Time: <%= r.date.strftime("%b %e, %l:%M %p") %></li>
        </ul> 
    <% end %> 
<% end %> 

<h4>Requests Received</h4>

<i> pending approval </i> 

    <ul> 

        <% @user.received_requests.each do |r| %>
           
            <% if r.accept.nil? %> 
            <li>From: <%= r.user.name %> - <%= link_to r.subject_line, request_path(r) %> - Received on <%= r.created_at.strftime("%b %e, %l:%M %p")%></li>
            <% end %>
    <% end %> 
    </ul>



<h4>Requests Sent</h4> 

<ul> 

<% @user.requests.each do |r| %>
    <li> To <%= recipient(r) %> - <%=link_to r.subject_line, request_path(r) %> - sent on: <%= r.created_at.strftime("%b %e, %l:%M %p") %> - Status: <%= request_status(r) %> </li>

    <% end %>
</ul> 

app/views/users/_request.html.erb
<h3> Upcoming Doggy Hangouts </h3>


 <% @user.received_requests.each do |r| %> 

    <% if r.accept == true %> 
        <p> Appointment with: </p> 
        <ul>
        <li>Owner: <%= r.user.name %></li>
        <li>Dog: <%= r.pet.name %></li>
        <li>Date & Time: <%= r.date.strftime("%b %e, %l:%M %p") %></li>
        </ul> 
    <% end %> 
<% end %> 

<h4>Requests Received</h4>

<i> pending approval </i> 

    <ul> 

        <% @user.received_requests.each do |r| %>
           
            <% if r.accept.nil? %> 
            <li>From: <%= r.user.name %> - <%= link_to r.subject_line, request_path(r) %> - Received on <%= r.created_at.strftime("%b %e, %l:%M %p")%></li>
            <% end %>
    <% end %> 
    </ul>



<h4>Requests Sent</h4> 

<ul> 

<% @user.requests.each do |r| %>
    <li> To <%= recipient(r) %> - <%=link_to r.subject_line, request_path(r) %> - sent on: <%= r.created_at.strftime("%b %e, %l:%M %p") %> - Status: <%= request_status(r) %> </li>

    <% end %>
</ul> 

app/views/users/new.html.erb
<h1> Sign up here! </h1> 

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user) do |f| %>
    <div class="field form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>
    </div>
    <br>
    <br>
    <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    </div> 
    <br>
    <br>
    <div class="field form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %> 
    </div>
    <br>
    <br>
    <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <br>
    <br>
    <div class="field form-group">
    <%= f.submit 'Create User', class: 'btn btn-success' %>
    </div>
<% end %> 

app/views/users/show.html.erb
<div class="container p-3 my-3 bg-primary text-white"><h1><%= @user.username %>'s Profile </h1></div>
<br>
<h4>Pets:</h4> 
<ul> 
<% @user.pets.each do |p| %>
     <li><%= link_to p.name, pet_path(p) %></li>
     <% end %>
 </ul>
 <% if @user.id == current_user.id %> 
 <%= link_to "Add a Pet", new_pet_path, class:"btn btn-info mb-3" %> 
 <% end %> 

 <%= render 'event' %> 

 