config/routes.rb
Rails.application.routes.draw do

  #sets my homepage 
  get '/' => 'sessions#welcome'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get'/popular_event' => 'listings#popular_event'

  resources :users do 
    resources :listings, only: [:index]
  end
  resources :locations 
  resources :events
  resources :pets
  resources :listings do 
    resources :events, only: [:new, :index]
  end
  
  resources :users do 
    resources :events, only: [:show]
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav_html.erb
<%= link_to "My Profile", user_path(current_user) %>
<%= link_to "All Listings", listings_path %>
<%= link_to "Events by Location", locations_path %>
<%= link_to "My Listings", user_listings_path(current_user)%>
<%= link_to "Create New Listing", new_listing_path %>
<%= link_to "Log Out", logout_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoggyHangouts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">

  <% if logged_in? %> 

  <div class="container">
  
  <nav class="navbar navbar-dark bg-dark">

  <a class="navbar-brand" href="/users/<%= current_user.id %>">My Profile</a>
  <a class="navbar-brand" href="/locations">Events by Location</a>
  <a class="navbar-brand" href="/listings">Listings</a>
  <a class="navbar-brand" href="/users/<%= current_user.id%>/listings">My Listings</a>
  <a class="navbar-brand" href="/listings/new">Create New Listing</a>
  <a class="navbar-brand" href="/logout">Log Out</a>

  </nav> 

  </div>

  <% end %> 

  <% if flash[:notice] %> 
  <div class="container">
  <div class="alert alert-success" role="alert"> 
    <%= flash[:notice] %>
    </div>
    </div>
    <% end %> 

    <% if flash[:error] %> 
  <div class="container">
  <div class="alert alert-danger" role="alert"> 
    <%= flash[:error] %>
  </div></div> 

  <% end %> 

  <div> 
  <%= @error %>
  </div> 

  
    <div class="container">
      <%= yield %>
    </div>

  
  </body>
</html>